[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "45aa1dbbc79c7efab33614bdca31f0c76062f16a"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "9760a75ac6b67cc90316cde6705975e7dce1a8be1ea29d0fcdd19a938d9a1cdb"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+0/TetGen.v1.5.1.aarch64-linux-gnu.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "254d1284345719040c391cb57f8f47ef8e651764"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "ece7b885297715499a2d2c09e3016ee35c2d821eae9c5f1878fabfddfcdcd4a3"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+0/TetGen.v1.5.1.aarch64-linux-musl.tar.gz"
[[TetGen]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5d72d1a564b422c7b0f57bed05e6c97909da8014"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "c816ba3946ffef56b0925561fb25b12f3e60e09f4b5ebdf71d35d0925c105343"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+0/TetGen.v1.5.1.armv7l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0d826e0046d0b801c73827ef1df99aa419c0d576"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "1f24bc8310f18e6f41562746881569b06991ff51e08fbeee15366edc27487562"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+0/TetGen.v1.5.1.armv7l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "d60270796e523b6c10a4d0ba0cc13b158fe44fdf"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "dce3a8232d64a9b2f534d80dd6a655e0bf2e90904f15e8a5017b964dbb093457"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+0/TetGen.v1.5.1.i686-linux-gnu.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "f3dc247a69345b2f202a82d7081d6597f9547330"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "92c0949d2fbef8b8a016dbee3601d26ca1ccb12f77aa4fb214cc591995c6704f"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+0/TetGen.v1.5.1.i686-linux-musl.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "4d7eb22bec4fe786c0d1ac09adda21dae3ec3d60"
os = "windows"

    [[TetGen.download]]
    sha256 = "d67e45eb033171b4a3cf8f083515a07e45200438861bb2b4d87e2864b0f3ebdd"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+0/TetGen.v1.5.1.i686-w64-mingw32.tar.gz"
[[TetGen]]
arch = "powerpc64le"
git-tree-sha1 = "77a7de9a1c3c2a1f9e58bfc74fcc0a68d6b6d0b6"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "16d7f44441ea97e4fae6c74e9c16e298bfce58b7c081cb40ae752245c8be9928"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+0/TetGen.v1.5.1.powerpc64le-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "11151ca6b17ae292a39d19692bc61e97e7f97897"
os = "macos"

    [[TetGen.download]]
    sha256 = "954c54544895030fce445b906205743c6d67d25f886baa6c9dc8e551f8784e6f"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+0/TetGen.v1.5.1.x86_64-apple-darwin.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "efd0453b645585e5144568d783465262f2d467f0"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "e683f1e7824f679b9e9f4edb60a3e5700eeba6834775807297f10e68b7ccad27"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+0/TetGen.v1.5.1.x86_64-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "e374583de0bd642b5630aa4711a7ee8665a5b333"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "59904339fa19f7099671eef76db1f9172ce2b633957df5e82c53425987fb1304"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+0/TetGen.v1.5.1.x86_64-linux-musl.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "9cf92a81526c2125ed77fab62daa6486c6ac6d51"
os = "freebsd"

    [[TetGen.download]]
    sha256 = "36dd081aae224f17eb270475875677fadecbb5fa916bd64cfb89355b6ffc9c55"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+0/TetGen.v1.5.1.x86_64-unknown-freebsd.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "c881c5450680670a1812093091892624231640fe"
os = "windows"

    [[TetGen.download]]
    sha256 = "8fece6df4a7bd7916ecb8e3579e40590254ee8cabbd61cc508f4dc92bee54171"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+0/TetGen.v1.5.1.x86_64-w64-mingw32.tar.gz"
