[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "1f2c1b2b80012387150091456ad755c490f74e77"
os = "macos"

    [[TetGen.download]]
    sha256 = "a074c4d0e05f1864968b7f831111aed6dd9ed1ff3ffd36baca859a856141a02c"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.3+0/TetGen.v1.5.3.aarch64-apple-darwin.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "1de35896218842d6ce13236a51e2dfd73287567b"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "a426de8d5f017a32a3ec1f6493e1c04f8761c7c067fd9b156d5ef8a6d380f513"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.3+0/TetGen.v1.5.3.aarch64-linux-gnu.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "83b764a75888d53fbea1f9133e69dfec939922df"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "9f44e432ecc643963b017cce6e04ab36254509743ee9dc77f6cb69638ebb7a33"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.3+0/TetGen.v1.5.3.aarch64-linux-musl.tar.gz"
[[TetGen]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b38830ac5c04086e89edb8159541c9b5b745a86a"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "06239d4ef309530fbad16ae551a77d1a057c999d9c9a4231a5fa51b70e7625fb"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.3+0/TetGen.v1.5.3.armv6l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4b321fed6c41616b6ff90156c2c6bd85f4579943"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "4eb0b3bdab085e3a5851da61c9b586d22d37e65435dc34e008b5732fde604e9f"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.3+0/TetGen.v1.5.3.armv6l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da1440a502bc3b1d3bc7745b180b35807486643f"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "89d21f3c19d2fe6c9e1c8990955ad9793cdf29a45265321896045035790dfede"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.3+0/TetGen.v1.5.3.armv7l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4d4ddd6b36da6f95673d39afadf70004d29f1cae"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "3cd76905b6e1500b8c9fe79d731c56dac366a6cb14c52e47b45a8d1c112a0aaf"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.3+0/TetGen.v1.5.3.armv7l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "7372bdd67dc42dc8579829635e64ec981c7d56c1"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "b2054e33efb2a2b6b0eac8daad195ef1d871fed93f3da75dfed806994301068d"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.3+0/TetGen.v1.5.3.i686-linux-gnu.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "126da87b86c9078be1a18ac009326a0ba2cd026f"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "7f6dade0f0e75f7be8e8e9a67cc9deaa7513f5ba93fe08458af4b3167dadb948"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.3+0/TetGen.v1.5.3.i686-linux-musl.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "f7d053c3dc926536ea78befd1d3243f7fd994cba"
os = "windows"

    [[TetGen.download]]
    sha256 = "ef0c30adc359e7b328fc4c9164afb6040173564ad810b440548c8c9a1fa07e7a"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.3+0/TetGen.v1.5.3.i686-w64-mingw32.tar.gz"
[[TetGen]]
arch = "powerpc64le"
git-tree-sha1 = "7de12ecf8b321a99e6854229144d8458d0fbc97e"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "78c42f9b2e4c32ca1e17140c0982b13079c4e990c855f91d9db595f762c36229"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.3+0/TetGen.v1.5.3.powerpc64le-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "cf8f12830e726eb6f02499d1435c7a2e9b08356d"
os = "macos"

    [[TetGen.download]]
    sha256 = "d83ef965f8152860466bc4cb2e49b271767197bc8170accac5cd087fcb500782"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.3+0/TetGen.v1.5.3.x86_64-apple-darwin.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "ff1cf743f1b13e45a169515ea60b781c1a8c4b98"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "01d93396a1a74f53f3a441a86d9ff4c0b455e22d63d2bc514e8eea8a8978ce77"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.3+0/TetGen.v1.5.3.x86_64-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "139f3eed57c8af355c1fe546b2ad4b774d1943a6"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "39681751c75bd9dfb1825528c7beae91ad8277eb1ef02840943d579f4d94a14c"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.3+0/TetGen.v1.5.3.x86_64-linux-musl.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "cf5499928c79d6de9a7aa1868cbfd6eeb494f6cd"
os = "freebsd"

    [[TetGen.download]]
    sha256 = "b5b92c7f2d67fde6ad85800314ca263b114bb32ba5dd513ec1b2e98ff10f96cf"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.3+0/TetGen.v1.5.3.x86_64-unknown-freebsd.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "71ac3d1222cf36471c1439d75adb9bbb22cd3e6f"
os = "windows"

    [[TetGen.download]]
    sha256 = "f83180e6c070bee991c9fecfffce4ffc96960bcd48abb698d92d601a034b5dfc"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.3+0/TetGen.v1.5.3.x86_64-w64-mingw32.tar.gz"
