[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "c2898d8ab143b743234e15a40b97fcf776d3bb56"
os = "macos"

    [[TetGen.download]]
    sha256 = "e35fd678286f0988b5239ab31346f6fc1c68872ec84c7047ef86a84eb59eaf18"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.aarch64-apple-darwin.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "50074641cd7b8d54db608f681133b3f873ab04dd"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "4aca13ede08421a3356830b97ee4b4f6eaed0d5bb7e8b0f0c58b167cddf83f48"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.aarch64-linux-gnu.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "3a086e7c25bb7cd5c3cf92187e9bf10ae4b1d76a"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "99387109fa616b3f62df6738329bcfb1a859cbf8b55770ef1b0bcede26d56de8"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.aarch64-linux-musl.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "1f7fb67e7af4f191ab4fc2d8eadbe383310f576d"
os = "freebsd"

    [[TetGen.download]]
    sha256 = "395a890bf63978dde90666f6aa0feb8f15b91aabf3c8d7b620dada4a2dc9877f"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.aarch64-unknown-freebsd.tar.gz"
[[TetGen]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1b7ddc6310ac592b6e01c133d62ff24ffc6a8e4a"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "405a34e2689c1f311a3b2facf2db9b883eced1aa0f751b2018b3d36e1f28f529"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.armv6l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "864353b5ebc63fc2ddf47ef81cf4be72634831dd"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "8b78e8e28781d53ea3c47904e79e8fd3d221312b2e07f887bc201700a737a304"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.armv6l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a4d6e6ba31e57e0a77346075e9be2083c2eff0b1"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "3faaf3e41fd2f4c59a0d9a8b96f554dfcc774a3f7b7e048b3cbac33921754762"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.armv7l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5f44f32fad1af4ea2002b31362e2c6a1bbce6b50"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "caca339899b0c06296b7b287ef245381af8bfa5e0b2ec1600582dcda8a18d220"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.armv7l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "e4ae8210f6f57a7bf3143043d19061d6267104fb"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "81e43cbf2a4a35b9e3d5a4c6ebd30b5b0556359b9698ecae940185b2fd404ac3"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.i686-linux-gnu.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "cf27fec1f37780531f66437c311bf9ca2fb2082e"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "283adafe69431640a7f37ca776a33db2a9f8f5471a8ce470964b852c2c356754"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.i686-linux-musl.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "a618bf171ee520fce4ffb1937abeb2d6998c5822"
os = "windows"

    [[TetGen.download]]
    sha256 = "30d74fefb7965b9d9ac3c1f62635c4e9956d9b6727e94375f6b378766f3587ad"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.i686-w64-mingw32.tar.gz"
[[TetGen]]
arch = "powerpc64le"
git-tree-sha1 = "f205ff33166c0dc20ea8e946b81a868d7149e42b"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "96c634678f5536df3390dd1bd5c543abdbb63c14496039c9d53d48228cb469c0"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.powerpc64le-linux-gnu.tar.gz"
[[TetGen]]
arch = "riscv64"
git-tree-sha1 = "bc2df42ca7568026ada2ea5fb5251a31d41d38e7"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "821797bd8f542814994a623745cde6bcc1d8372e55e771b6ea8b5868a87ee54a"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.riscv64-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "bb998f9dc36c849b2d80cc8d0866433a8010975a"
os = "macos"

    [[TetGen.download]]
    sha256 = "af410b997a6123966e5fb7e6a934691cc84b041a04e1e9b71e5cafbd5443dc66"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.x86_64-apple-darwin.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "bb2c94289748463d6d4531eaa24c6e0831d059da"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "26021153f774b806f6fb2e8ae877e7e913abc8ac6b0028abd2988d327746694f"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.x86_64-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "e4b8ef783eed8de5b77ac27297b9498b6a6c4519"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "14cfc3f36a1f434021551c0fe7feeb7360d0c015fe6de867dad80ba292d6578c"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.x86_64-linux-musl.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "87da863ff7917bd9d7c699eff0b8233961abe674"
os = "freebsd"

    [[TetGen.download]]
    sha256 = "4f47a95428f7f7e51c2fd2eb32608fec028f6b7a6ec78ef6c077dce522b86d80"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.x86_64-unknown-freebsd.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "06bbde4b80dd9c6c81efe7321d39855789188fa8"
os = "windows"

    [[TetGen.download]]
    sha256 = "782f31d2590dcb98cb1a03b2c80e4e6b9d7722247e26f5f16e580d08ffa91365"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.x86_64-w64-mingw32.tar.gz"
