[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "5b8c69fd749e1e1a807ff09225bf953a633209cc"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "c1036e07b5bd25e9aa2ca4ce5b448d8c96e1b27bad4f5d154fb2d4fccaf93c6f"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.aarch64-linux-gnu.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "1ff6fe52b691a9e5277db6e9c44f43d0db311c9d"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "ec61998a0af3e80cd63ee964e519c6ed790650ffdd414ba402c1dd676e701e6c"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.aarch64-linux-musl.tar.gz"
[[TetGen]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "06a00f4352a41637189f15bb7041d68ccf1acd98"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "4df432240c007f5e2f960d0368c6221726a6dc847c6c1bfbbfe464bc1707c85e"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.armv7l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aea4737599852f2db2653ded2ea543a9a8d17fac"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "c5b8a7c352a75d788eac7940d78ea2d8adda16927836469753815276f3e68466"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.armv7l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "5d95f3c65100d96ea561d462ba6655365ec00c67"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "420b0ecea15c37774225b8aea1f62cb47d0bf5da5f7365a0cbedcc35c692a76b"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.i686-linux-gnu.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "bf0ad584d1a14878de272238501b893c8041385f"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "b882a161faa3a2cdb60e845e76332f24c94166f7331d652b68d9a0b401ccc92c"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.i686-linux-musl.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "95f353d70fde77da2c992a8fe781ecc963b1adf8"
os = "windows"

    [[TetGen.download]]
    sha256 = "2ceca1b2bc01ba917002e3926e36845ce897ec3543439faaeb4cb469c0f64b29"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.i686-w64-mingw32.tar.gz"
[[TetGen]]
arch = "powerpc64le"
git-tree-sha1 = "3369e4534c9b36842620b2b865203729acc983c2"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "78fc4d921088a84804b1a4c7a8b0829b42c3068774cfb0a410d2f882c9b82263"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.powerpc64le-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "b0d9ce67ab402b437d231e46a97cf15976aa596f"
os = "macos"

    [[TetGen.download]]
    sha256 = "f12d2b3ca619a8e34410a23a0cec707abc8be402aabcbba913bb60485e9b4dbb"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-apple-darwin.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "772a7617bca0416fde41cba014e7743d55290172"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "12382bae9dc5d2a763b089f776b629df4e55882949d3b7feda5a599d9515c30e"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "b0445425738b99252be94ccce3f3c1cedcd77697"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "629f519c1f3c3f33b64176baa57a1e3b5177ae545aff5a616d39e98d724418b0"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-linux-musl.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "be11f25221807999fc2096ddf736f9280d797a47"
os = "freebsd"

    [[TetGen.download]]
    sha256 = "157a518c93989df5d40829883e2ea64f0da5c44c21fcb996e7a264b84d4a68c5"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-unknown-freebsd.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "2cf99c735686e27de4ad6bbd628bcc530a2032b3"
os = "windows"

    [[TetGen.download]]
    sha256 = "45de2339a108d3a1b2b40753a875960344ce1b6bf41cd8ab495d9ccb6ec73999"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+1/TetGen.v1.5.1.x86_64-w64-mingw32.tar.gz"
