[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "2da3f92d5fddaf05942868367e9ac412b208760f"
os = "macos"

    [[TetGen.download]]
    sha256 = "0db88863619370f87b479e1eac0af85b71d47f6530e6b8f64078c1d52489dcbb"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.aarch64-apple-darwin.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "50074641cd7b8d54db608f681133b3f873ab04dd"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "4aca13ede08421a3356830b97ee4b4f6eaed0d5bb7e8b0f0c58b167cddf83f48"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.aarch64-linux-gnu.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "3a086e7c25bb7cd5c3cf92187e9bf10ae4b1d76a"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "99387109fa616b3f62df6738329bcfb1a859cbf8b55770ef1b0bcede26d56de8"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.aarch64-linux-musl.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "2e7fd21b5e32e2677d2a01c41a3d26a81a4979fc"
os = "freebsd"

    [[TetGen.download]]
    sha256 = "54761ead6b714f52a7b3892b073f8d4ce50107fd16d0aef5940a8e337baaa085"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.aarch64-unknown-freebsd.tar.gz"
[[TetGen]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1b7ddc6310ac592b6e01c133d62ff24ffc6a8e4a"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "405a34e2689c1f311a3b2facf2db9b883eced1aa0f751b2018b3d36e1f28f529"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.armv6l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "864353b5ebc63fc2ddf47ef81cf4be72634831dd"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "8b78e8e28781d53ea3c47904e79e8fd3d221312b2e07f887bc201700a737a304"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.armv6l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a4d6e6ba31e57e0a77346075e9be2083c2eff0b1"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "3faaf3e41fd2f4c59a0d9a8b96f554dfcc774a3f7b7e048b3cbac33921754762"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.armv7l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5f44f32fad1af4ea2002b31362e2c6a1bbce6b50"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "caca339899b0c06296b7b287ef245381af8bfa5e0b2ec1600582dcda8a18d220"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.armv7l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "e4ae8210f6f57a7bf3143043d19061d6267104fb"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "81e43cbf2a4a35b9e3d5a4c6ebd30b5b0556359b9698ecae940185b2fd404ac3"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.i686-linux-gnu.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "cf27fec1f37780531f66437c311bf9ca2fb2082e"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "283adafe69431640a7f37ca776a33db2a9f8f5471a8ce470964b852c2c356754"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.i686-linux-musl.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "a2e266a564dc721aba146ae8f37d6ffe2804d6ba"
os = "windows"

    [[TetGen.download]]
    sha256 = "3f601adfda4a091f2212cbb8d921cb479d024f8f80639076e859459bc4921900"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.i686-w64-mingw32.tar.gz"
[[TetGen]]
arch = "powerpc64le"
git-tree-sha1 = "f205ff33166c0dc20ea8e946b81a868d7149e42b"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "96c634678f5536df3390dd1bd5c543abdbb63c14496039c9d53d48228cb469c0"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.powerpc64le-linux-gnu.tar.gz"
[[TetGen]]
arch = "riscv64"
git-tree-sha1 = "a701f59d2fc4c7c779ef9ba4ccd0b384e8da3e27"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "66418368d6cb2bfd845e79a0e6129ea373cf7eaca176860b79e9423245603077"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.riscv64-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "d3c20faceb27c3f9847b3367563ea0842db120ac"
os = "macos"

    [[TetGen.download]]
    sha256 = "b03df4b5f47f52762b1e204fadfa2dbfc694a4f23f03627d08db039a8be13952"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.x86_64-apple-darwin.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "bb2c94289748463d6d4531eaa24c6e0831d059da"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "26021153f774b806f6fb2e8ae877e7e913abc8ac6b0028abd2988d327746694f"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.x86_64-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "e4b8ef783eed8de5b77ac27297b9498b6a6c4519"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "14cfc3f36a1f434021551c0fe7feeb7360d0c015fe6de867dad80ba292d6578c"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.x86_64-linux-musl.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "f3c46d800ac3ad05371c9a9abb2a98d13dcd2b96"
os = "freebsd"

    [[TetGen.download]]
    sha256 = "576bd97188c2d2a6c1ad36b79ae8eeaa5f503a1b490b845851035c4fd17ac5e8"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.x86_64-unknown-freebsd.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "0822bd102b1a7a6c5a3cc2f0b9cef5829b5d3ea7"
os = "windows"

    [[TetGen.download]]
    sha256 = "2438b64e252c5d2bcc458836b92f2425b95c0ae519c1e0c65fd3b643bc4ad792"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.4+0/TetGen.v1.5.4.x86_64-w64-mingw32.tar.gz"
