[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "bfd25e682b87e2c57ec27319679cf46ebf46d9a8"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "7e8f3e094dbc9a9775b231ab75dc09bbd38cd4c89eab2bfcfaedd97e836df51f"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+2/TetGen.v1.5.1.aarch64-linux-gnu.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "c12e1b600be5ccc707dac33f158a018b76ac305c"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "064a25c0139508f01ce757af6faa144587c83b1fcfe969c60eb92f09386da833"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+2/TetGen.v1.5.1.aarch64-linux-musl.tar.gz"
[[TetGen]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "23e234afeaf7fb68324ad4e8bdd393b86f1cf17e"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "5a14a542badecf2f573427b42e26d5301783a47c801f7b5d4cd7cceb1b1086f4"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+2/TetGen.v1.5.1.armv7l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3a4453fffd00022ab0350eacb811565ed4652ff7"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "5d785d0ef1824397a1fe5e237cda834f2fec05f53f94cc01b7d3708f4c76922e"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+2/TetGen.v1.5.1.armv7l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "e1fc7bd9fb533173823eb2bc41649c42bb14f121"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "bc228640fcda9bb643143863778a7385129b255309de8f46dd6fd72f49a153cf"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+2/TetGen.v1.5.1.i686-linux-gnu.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "8ba73185b8433cba4978b96d562b35adb2219d0f"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "11fcca56c21f9b119dc5bfa39a412fdd2146c8197d2811f8c48e25dba599cadb"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+2/TetGen.v1.5.1.i686-linux-musl.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "e7bdfb6245cd865caf1ecee588ae60393f1780f2"
os = "windows"

    [[TetGen.download]]
    sha256 = "ed0a6af4d299f9c08b1fc98afe897ee77a71f810f7ca9fea4387c8a8030d124e"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+2/TetGen.v1.5.1.i686-w64-mingw32.tar.gz"
[[TetGen]]
arch = "powerpc64le"
git-tree-sha1 = "48d7cc0d65d3e9c9135b931baf43c08b4231eae9"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "6951e3219e48b55a8deaeeb53445eb4ce5c0c7eb0030f6b0df9b88f1c1219e3c"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+2/TetGen.v1.5.1.powerpc64le-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "203ab90a75cd9f37b2b6192dc551569d0d793377"
os = "macos"

    [[TetGen.download]]
    sha256 = "590a0fc772cbbe6fc6118a0a16aebd9c5a0b43e9cc53bd0d3a16a5738048cbb6"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+2/TetGen.v1.5.1.x86_64-apple-darwin.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "d99f93c0f125d68bbb536430f587d430d7d6962e"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "938078001226c48fd85b9f441b532bf7c3f34b95fd111572368baba70ba9c728"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+2/TetGen.v1.5.1.x86_64-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "8e24cf14e55b7934b4849725e6422637626f48c5"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "ffcd287b1b7ce96020ba3ac4c5bfa934387288891099b715d04d8b266bf66be4"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+2/TetGen.v1.5.1.x86_64-linux-musl.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "ef566bd4e2b432d669a11e6b11acfdabd31b0376"
os = "freebsd"

    [[TetGen.download]]
    sha256 = "30f951a84d4ea714cc21318d0526dee0991bf8dff9ecb82e7a3f20c42319ea32"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+2/TetGen.v1.5.1.x86_64-unknown-freebsd.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "c1daecf0089b9e54e8cf0ba3ee9d791e37704d80"
os = "windows"

    [[TetGen.download]]
    sha256 = "35c71ccc3c4f967c2952bc60f31f128582d6ec587d1c1bd6c79357e5b37266d6"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.1+2/TetGen.v1.5.1.x86_64-w64-mingw32.tar.gz"
