[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "e218448d70fa9b56068f40410582dc80dab999d3"
os = "macos"

    [[TetGen.download]]
    sha256 = "65eabe33ac5a8e447db2f4156b8417989ad04ee394f2ff7f8b954273d42eff0a"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.2+0/TetGen.v1.5.2.aarch64-apple-darwin.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "361e18c9df5567767d021adf941dcad9d9e420c8"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "cec3fb0c452764ee5c850c3e42ada91cad9db8d92249c3c8c454aac6e535c817"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.2+0/TetGen.v1.5.2.aarch64-linux-gnu.tar.gz"
[[TetGen]]
arch = "aarch64"
git-tree-sha1 = "f089eb9609adf318fefd727a97ab3661a31a53cd"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "a4a513d17258bc2c3dedec5b9657061382810b13cadcc997748109bd366b97b2"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.2+0/TetGen.v1.5.2.aarch64-linux-musl.tar.gz"
[[TetGen]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b12a7598d53b38f13dcf5e1b341b7010d808450b"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "55c387c366dc9e512ed48fccd25e3733c18c97df9bc848909196e4d46da20478"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.2+0/TetGen.v1.5.2.armv6l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d19788fefcf278607a7d33737d26d186a29bee60"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "300949afcc11b37ffbeae9911ab75b230733833f44ee712bbaf84d2d4b7a46a3"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.2+0/TetGen.v1.5.2.armv6l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a9e5219fe06b4d405204b360bfd6ac6f87a15152"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "bb5d0302538fa16502381b88f67ef26546869d0383b031068b38dd84cac2d4db"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.2+0/TetGen.v1.5.2.armv7l-linux-gnueabihf.tar.gz"
[[TetGen]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d818df722774b07aa1d9584828880b7392a76642"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "3562d879fef94d27392885d445fd51226ef91e823d6e5c31cec846e44fa586cb"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.2+0/TetGen.v1.5.2.armv7l-linux-musleabihf.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "a48f3e6e660de9f94062166b713b76b23dccc227"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "9479db77f8fbf47aeeeeb306436c069e99e83ea79d7e2e584b76c470c2d5c028"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.2+0/TetGen.v1.5.2.i686-linux-gnu.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "4684a5eafe17ef29d857fc1aa4db8ee4436ebd6d"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "0f84163396bd86362f1bebd544a70125f3ab0d1eeb6ed2549cacfda248edf63e"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.2+0/TetGen.v1.5.2.i686-linux-musl.tar.gz"
[[TetGen]]
arch = "i686"
git-tree-sha1 = "d2bcde395e60a8018559c13973502bd31049ff15"
os = "windows"

    [[TetGen.download]]
    sha256 = "bb9fb131e82fc1518333395c5308a3bb24bf9d1ad20c7914ff556fa0c4b3f09c"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.2+0/TetGen.v1.5.2.i686-w64-mingw32.tar.gz"
[[TetGen]]
arch = "powerpc64le"
git-tree-sha1 = "3d0e3c63b10cbc536b614294fdcdbda9c9952d9c"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "3371d7377adaabdc69257335054370ba7809dc4bab98d510deaa3d171b96d5cd"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.2+0/TetGen.v1.5.2.powerpc64le-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "bd5f043c44219fd4a5099c5352f282700e158586"
os = "macos"

    [[TetGen.download]]
    sha256 = "13ab96c2be3e0616d5efcf0bcc78708b78b5751972598792a2442b2517b16811"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.2+0/TetGen.v1.5.2.x86_64-apple-darwin.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "48fafed2eddbcd8901a4d69704624d6dcb931a9e"
libc = "glibc"
os = "linux"

    [[TetGen.download]]
    sha256 = "13533478d113734a56c957fe681efc7d52e32bf15d67c31aca4cbd2cae7b5f86"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.2+0/TetGen.v1.5.2.x86_64-linux-gnu.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "65f6b03d509eab3c3546a0d7b271837f18f0d73c"
libc = "musl"
os = "linux"

    [[TetGen.download]]
    sha256 = "f3239aaebb9293065f4d2018af02c3ed27a92ee84ba9de614cde7141d3db033a"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.2+0/TetGen.v1.5.2.x86_64-linux-musl.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "cbf888245ce838a76ba569e07eba7d4e0ae682cc"
os = "freebsd"

    [[TetGen.download]]
    sha256 = "2101b08c86caa4c6dad782a0438f5d78bf32a0a47bedad8e054bb4bcfe7dd304"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.2+0/TetGen.v1.5.2.x86_64-unknown-freebsd.tar.gz"
[[TetGen]]
arch = "x86_64"
git-tree-sha1 = "07de42f5a70bb62502b6b15f56549984fe448aa4"
os = "windows"

    [[TetGen.download]]
    sha256 = "cadf7058fb9c96748cbe0842759992f864f3f92934107ba699f0ac021e045859"
    url = "https://github.com/JuliaBinaryWrappers/TetGen_jll.jl/releases/download/TetGen-v1.5.2+0/TetGen.v1.5.2.x86_64-w64-mingw32.tar.gz"
